version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "namedivider-python"
    schedule:
      interval: weekly
